#server:
#  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/DB_canboard
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
